name: moengine_gal
description: moengine for avg/galgame
version: 1.0.0
author:
homepage: https://github.com/moengine-project/moengine/tree/master/packages/moengine_gal

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  moengine:
    path: ../moengine
  moengine_moex:
    path: ../moengine_moex

dev_dependencies:
  flutter_test:
    sdk: flutter
  test_coverage: ^0.4.0

flutter:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
