os:
  - linux
sudo: false
language: dart
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libstdc++6
      - fonts-noto
cache:
  directories:
    - "$HOME/.pub-cache"
install:
  - git clone https://github.com/flutter/flutter.git
  - export PATH=./flutter/bin:$PATH
  - flutter doctor
script:
  - flutter packages get
  - flutter analyze --no-pub --no-current-package lib/ test/
  - flutter test --no-pub test/