name: moengine_moex
description: A new Flutter package.
version: 1.0.0
author:
homepage: https://github.com/moengine-project/moengine/tree/master/packages/moengine_moex

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  test_coverage: ^0.4.0

flutter:

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
